export interface WeatherCodeInfo {
  code: number;
  description: string;
  category: 'clear' | 'clouds' | 'fog' | 'drizzle' | 'rain' | 'snow' | 'thunderstorm';
  icon: string; // Lucide icon name identifier
  accentColor: string;
  badgeText: string;
}

export const WMO_WEATHER_CODES: Record<number, WeatherCodeInfo> = {
  0: {
    code: 0,
    description: 'Clear sky',
    category: 'clear',
    icon: 'Sun',
    accentColor: 'text-amber-400',
    badgeText: 'Clear',
  },
  1: {
    code: 1,
    description: 'Mainly clear',
    category: 'clear',
    icon: 'SunDim',
    accentColor: 'text-amber-300',
    badgeText: 'Mostly Clear',
  },
  2: {
    code: 2,
    description: 'Partly cloudy',
    category: 'clouds',
    icon: 'CloudSun',
    accentColor: 'text-sky-300',
    badgeText: 'Partly Cloudy',
  },
  3: {
    code: 3,
    description: 'Overcast',
    category: 'clouds',
    icon: 'Cloud',
    accentColor: 'text-slate-400',
    badgeText: 'Overcast',
  },
  45: {
    code: 45,
    description: 'Fog',
    category: 'fog',
    icon: 'CloudFog',
    accentColor: 'text-slate-400',
    badgeText: 'Foggy',
  },
  48: {
    code: 48,
    description: 'Depositing rime fog',
    category: 'fog',
    icon: 'CloudFog',
    accentColor: 'text-teal-300',
    badgeText: 'Rime Fog',
  },
  51: {
    code: 51,
    description: 'Light drizzle',
    category: 'drizzle',
    icon: 'CloudDrizzle',
    accentColor: 'text-cyan-400',
    badgeText: 'Light Drizzle',
  },
  53: {
    code: 53,
    description: 'Moderate drizzle',
    category: 'drizzle',
    icon: 'CloudDrizzle',
    accentColor: 'text-cyan-400',
    badgeText: 'Moderate Drizzle',
  },
  55: {
    code: 55,
    description: 'Dense drizzle',
    category: 'drizzle',
    icon: 'CloudDrizzle',
    accentColor: 'text-cyan-500',
    badgeText: 'Dense Drizzle',
  },
  56: {
    code: 56,
    description: 'Light freezing drizzle',
    category: 'drizzle',
    icon: 'CloudSnow',
    accentColor: 'text-blue-300',
    badgeText: 'Freezing Drizzle',
  },
  57: {
    code: 57,
    description: 'Dense freezing drizzle',
    category: 'drizzle',
    icon: 'CloudSnow',
    accentColor: 'text-blue-400',
    badgeText: 'Freezing Drizzle',
  },
  61: {
    code: 61,
    description: 'Slight rain',
    category: 'rain',
    icon: 'CloudRain',
    accentColor: 'text-blue-400',
    badgeText: 'Light Rain',
  },
  62: {
    code: 62,
    description: 'Moderate rain',
    category: 'rain',
    icon: 'CloudRain',
    accentColor: 'text-blue-500',
    badgeText: 'Moderate Rain',
  },
  63: {
    code: 63,
    description: 'Heavy rain',
    category: 'rain',
    icon: 'CloudRain',
    accentColor: 'text-indigo-400',
    badgeText: 'Heavy Rain',
  },
  65: {
    code: 65,
    description: 'Heavy intensity rain',
    category: 'rain',
    icon: 'CloudRain',
    accentColor: 'text-indigo-500',
    badgeText: 'Torrential Rain',
  },
  66: {
    code: 66,
    description: 'Light freezing rain',
    category: 'rain',
    icon: 'CloudSnow',
    accentColor: 'text-cyan-300',
    badgeText: 'Freezing Rain',
  },
  67: {
    code: 67,
    description: 'Heavy freezing rain',
    category: 'rain',
    icon: 'CloudSnow',
    accentColor: 'text-cyan-400',
    badgeText: 'Heavy Freezing Rain',
  },
  71: {
    code: 71,
    description: 'Slight snowfall',
    category: 'snow',
    icon: 'Snowflake',
    accentColor: 'text-sky-200',
    badgeText: 'Light Snow',
  },
  73: {
    code: 73,
    description: 'Moderate snowfall',
    category: 'snow',
    icon: 'Snowflake',
    accentColor: 'text-sky-300',
    badgeText: 'Moderate Snow',
  },
  75: {
    code: 75,
    description: 'Heavy snowfall',
    category: 'snow',
    icon: 'Snowflake',
    accentColor: 'text-sky-100',
    badgeText: 'Heavy Snow',
  },
  77: {
    code: 77,
    description: 'Snow grains',
    category: 'snow',
    icon: 'Snowflake',
    accentColor: 'text-sky-200',
    badgeText: 'Snow Grains',
  },
  80: {
    code: 80,
    description: 'Slight rain showers',
    category: 'rain',
    icon: 'CloudRain',
    accentColor: 'text-blue-400',
    badgeText: 'Passing Showers',
  },
  81: {
    code: 81,
    description: 'Moderate rain showers',
    category: 'rain',
    icon: 'CloudRain',
    accentColor: 'text-blue-500',
    badgeText: 'Rain Showers',
  },
  82: {
    code: 82,
    description: 'Violent rain showers',
    category: 'rain',
    icon: 'CloudLightning',
    accentColor: 'text-indigo-500',
    badgeText: 'Violent Showers',
  },
  85: {
    code: 85,
    description: 'Slight snow showers',
    category: 'snow',
    icon: 'CloudSnow',
    accentColor: 'text-sky-200',
    badgeText: 'Snow Showers',
  },
  86: {
    code: 86,
    description: 'Heavy snow showers',
    category: 'snow',
    icon: 'CloudSnow',
    accentColor: 'text-sky-100',
    badgeText: 'Heavy Snow Showers',
  },
  95: {
    code: 95,
    description: 'Thunderstorm',
    category: 'thunderstorm',
    icon: 'CloudLightning',
    accentColor: 'text-amber-400',
    badgeText: 'Thunderstorm',
  },
  96: {
    code: 96,
    description: 'Thunderstorm with slight hail',
    category: 'thunderstorm',
    icon: 'CloudLightning',
    accentColor: 'text-amber-300',
    badgeText: 'Thunderstorm & Hail',
  },
  99: {
    code: 99,
    description: 'Thunderstorm with heavy hail',
    category: 'thunderstorm',
    icon: 'CloudLightning',
    accentColor: 'text-red-400',
    badgeText: 'Severe Thunderstorm',
  },
};

export function getWeatherCodeInfo(code: number): WeatherCodeInfo {
  return (
    WMO_WEATHER_CODES[code] || {
      code,
      description: 'Variable atmospheric conditions',
      category: 'clouds',
      icon: 'Cloud',
      accentColor: 'text-slate-300',
      badgeText: 'Variable',
    }
  );
}
